### List
GET http://127.0.0.1:8000/api/admin
Accept: application/json

### Store
POST http://127.0.0.1:8000/api/admin
Accept: application/json
Content-Type: application/json

{
  "name": "admin",
  "email": "admin@b.co",
  "password": "admin12",
  "user_information": "{'address':'address','phone':'0123456789','birthday':'9-03-02','gender':'gender','photo':'photo','blood_group':'blood_group'}"
}

### Show
GET http://127.0.0.1:8000/api/admin/17
Accept: application/json

### Update
PUT http://127.0.0.1:8000/api/admin/5
Accept: application/json
Content-Type: application/json

{
  "name": "admin",
  "email": "admin@b.co",
  "password": "admin1234g",
  "user_information": "{'address':'addregss','phone':'0123456g789','birthday':'9-03-02','gender':'gender','photo':'photo','blood_group':'blood_group'}"
}

### Delete
DELETE  http://127.0.0.1:8000/api/admin/5
Accept: application/json