### List
GET http://127.0.0.1:8000/api/admin
Accept: application/json

### Store
POST http://127.0.0.1:8000/api/admin
Accept: application/json
Content-Type: application/json

{
  "name": "abdul1",
  "email": "abdul1@b.co",
  "password": "123456",
  "gender": "female",
  "birthday": "birthday",
  "phone": "phone",
  "address": "address",
  "blood_group": "blood_group",
  "photo": "photo.jpg"
}

### Show
GET http://127.0.0.1:8000/api/admin/17
Accept: application/json

### Update
PUT http://127.0.0.1:8000/api/admin/20
Accept: application/json
Content-Type: application/json

{
  "name": "admin",
  "email": "admin@b.co",
  "password": "admin1234g",
  "gender": "male",
  "birthday": "birthday",
  "phone": "phone",
  "address": "address",
  "blood_group": "blood_group",
  "photo": "photo.jpg"
}

### Delete
DELETE  http://127.0.0.1:8000/api/admin/5
Accept: application/json