### List
GET http://127.0.0.1:8000/api/routines
Accept: application/json

### Store
POST http://127.0.0.1:8000/api/routines
Accept: application/json
Content-Type: application/json

{
  "day": "saturday",
  "starting_hour": "10",
  "starting_minute": "1",
  "ending_hour": "00",
  "ending_minute": "00"
}

### Show
GET http://127.0.0.1:8000/api/routines/3
Accept: application/json

### Update
PUT http://127.0.0.1:8000/api/routines/2
Accept: application/json
Content-Type: application/json

{
  "day": "sunday",
  "starting_hour": "10",
  "starting_minute": "1",
  "ending_hour": "00",
  "ending_minute": "00"
}

### Delete
DELETE  http://127.0.0.1:8000/api/routines/3
Accept: application/json