### List
GET http://127.0.0.1:8000/api/teachers
Accept: application/json

### Store
POST http://127.0.0.1:8000/api/teachers
Accept: application/json
Content-Type: application/json

{
  "name": "teacher",
  "email": "teacher@b.co",
  "password": "123456",
  "user_information": "{'address':'address','phone':'0123456789','birthday':'9-03-02','gender':'gender','photo':'photo','blood_group':'blood_group','designation':'teacher'}"
}

### Show
GET http://127.0.0.1:8000/api/teachers/1
Accept: application/json

### Update
PUT http://127.0.0.1:8000/api/teachers/17
Accept: application/json
Content-Type: application/json

{
  "name": "nazim",
  "email": "nazim@b.co",
  "password": "123456",
  "user_information": "{'address':'addregss','phone':'0123456g789','birthday':'9-03-02','gender':'gender','photo':'photo','blood_group':'blood_group'}"
}

### Delete
DELETE  http://127.0.0.1:8000/api/teachers/1
Accept: application/json